import { useEffect, useState } from "react";
import { Check, CreditCard, Loader2, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { api, apiError } from "@/lib/api";

export default function Billing() {
  const [data, setData] = useState(null); const [busy, setBusy] = useState("");
  useEffect(() => { api.get("/billing/catalog").then((r) => setData(r.data)).catch((e) => toast.error(apiError(e))); }, []);
  const claim = async () => { setBusy("viewer"); try { const { data: ent } = await api.post("/billing/claim-viewer"); setData((p) => ({ ...p, entitlement: ent })); toast.success("Viewer sandbox access claimed"); } catch (e) { toast.error(apiError(e)); } finally { setBusy(""); } };
  const checkout = async (plan) => { setBusy(plan); try { const { data: r } = await api.post("/billing/checkout", { plan }); window.location.assign(r.checkout_url); } catch (e) { toast.error(apiError(e)); setBusy(""); } };
  return <div className="mx-auto max-w-6xl space-y-6 p-6"><div><p className="label-mono text-cyan-300">ACCESS & BILLING</p><h1 className="mt-1 font-display text-3xl font-extrabold">Choose your investigation workspace</h1><p className="mt-2 max-w-2xl text-sm text-slate-400">Guest and sample evidence stays free. Paid plans unlock server-enforced investigation capabilities; checkout uses Stripe test mode when configured.</p></div>{data?.entitlement && <div className="panel flex flex-wrap items-center gap-3 p-4"><ShieldCheck size={18} className="text-emerald-400" /><span className="text-sm text-slate-300">Current entitlement: <b className="uppercase text-cyan-300">{data.entitlement.plan}</b> · {data.entitlement.status}</span></div>}<div className="grid gap-4 lg:grid-cols-3">{(data?.plans || []).map((plan) => <section key={plan.id} className={`panel flex flex-col p-5 ${plan.id === "pro" ? "border-cyan-400/50" : ""}`}><div className="flex items-start justify-between"><div><h2 className="font-display text-xl font-semibold">{plan.name}</h2><p className="mt-1 text-xs text-slate-400">{plan.description}</p></div>{plan.id === "pro" && <span className="rounded-full bg-cyan-400/15 px-2 py-1 font-mono text-[10px] uppercase text-cyan-300">Popular</span>}</div><div className="my-5 font-mono text-3xl">{plan.amount === 0 ? "Free" : `$${(plan.amount / 100).toFixed(0)}${plan.interval ? ` / ${plan.interval}` : ""}`}</div><ul className="mb-6 flex-1 space-y-2 text-xs text-slate-300">{plan.features.map((f) => <li key={f} className="flex gap-2"><Check size={14} className="shrink-0 text-emerald-400" />{f}</li>)}</ul>{plan.id === "viewer" ? <button onClick={claim} disabled={!!busy} className="inline-flex items-center justify-center gap-2 rounded bg-slate-700 px-4 py-2 font-mono text-[11px] uppercase tracking-wider text-slate-100 hover:bg-slate-600">{busy === "viewer" && <Loader2 size={13} className="animate-spin" />}Claim free Viewer</button> : <button onClick={() => checkout(plan.id)} disabled={!!busy || !plan.price_id_configured} className="inline-flex items-center justify-center gap-2 rounded bg-cyan-400 px-4 py-2 font-mono text-[11px] font-semibold uppercase tracking-wider text-slate-950 hover:bg-cyan-300 disabled:cursor-not-allowed disabled:opacity-50">{busy === plan.id ? <Loader2 size={13} className="animate-spin" /> : <CreditCard size={13} />}{plan.price_id_configured ? "Continue to secure checkout" : "Price not configured"}</button>}</section>)}</div></div>;
}
