import { useCallback, useEffect, useMemo, useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { MapContainer, TileLayer, CircleMarker, Popup, useMap } from "react-leaflet";
import { toast } from "sonner";
import { Search, Crosshair, ShieldAlert, Check, Waves, Ship, Clock, FileCheck, BookOpen, ExternalLink } from "lucide-react";
import { api, apiError, fmtTime, pct, hasRole } from "@/lib/api";
import { useAuth } from "@/context/AuthContext";
import { StatusBadge } from "@/components/StatusBadge";
import { DetectorPrecision } from "@/components/dashboard/DetectorPrecision";
import { useLive } from "@/context/LiveFeed";
import { OSM_URL, TILE_PERF } from "@/components/map/tiles";

const MAP_CENTER = [20, 12];
const COLORS = { probable: "#c2410c", analyst_confirmed: "#006a61", possible: "#b26a00", insufficient_evidence: "#707881", indeterminate: "#8a63d2" };
const coordsOf = (c) => { const p = c?.centroid?.coordinates || c?.spill_observation?.centroid?.coordinates; return Array.isArray(p) && Number.isFinite(+p[0]) && Number.isFinite(+p[1]) ? [+p[1], +p[0]] : null; };
const parseCoord = (q) => { const m = q.trim().match(/^(-?\d+(?:\.\d+)?)\s*[, ]\s*(-?\d+(?:\.\d+)?)$/); if (!m) return null; const a = [+m[1], +m[2]]; if (Math.abs(a[0]) <= 90 && Math.abs(a[1]) <= 180) return a; if (Math.abs(a[1]) <= 90 && Math.abs(a[0]) <= 180) return [a[1], a[0]]; return null; };
const MapFocus = ({ target }) => { const map = useMap(); useEffect(() => { if (target) map.flyTo(target, Math.max(map.getZoom(), 7), { duration: 0.7 }); }, [map, target]); return null; };
const caseColor = (c) => COLORS[c.attribution_status] || "#007bb9";

function CaseMap({ cases, selected, onSelect, target }) {
  return <div className="relative h-full min-h-[540px] overflow-hidden rounded-xl border" style={{ borderColor: "var(--border-highlight)", background: "#f2f4f6" }} data-testid="dashboard-map">
    <MapContainer center={MAP_CENTER} zoom={3} minZoom={2} maxZoom={15} className="h-full w-full" zoomControl><TileLayer url={OSM_URL} className="dark-tiles" {...TILE_PERF} attribution="&copy; OpenStreetMap contributors" /><MapFocus target={target} />
      {cases.map((c) => { const pos = coordsOf(c); if (!pos) return null; const color = caseColor(c); return <CircleMarker key={c.id} center={pos} radius={selected?.id === c.id ? 12 : 8} pathOptions={{ color, fillColor: color, fillOpacity: 0.78, weight: selected?.id === c.id ? 3 : 1 }} eventHandlers={{ click: () => onSelect(c) }} data-testid={`map-case-${c.case_number}`}><Popup><div className="min-w-[210px] text-xs"><div className="mb-1 flex items-center justify-between gap-2"><b className="font-mono text-cyan-300">{c.case_number}</b><span style={{ color }}>{(c.attribution_status || "unknown").replaceAll("_", " ")}</span></div><div className="text-slate-300">{c.source || "Satellite observation"}</div><div className="mt-1 font-mono text-[10px] text-slate-400">{pos[0].toFixed(4)}, {pos[1].toFixed(4)} · {fmtTime(c.acquisition_time)}</div><button className="mt-2 inline-flex items-center gap-1 text-cyan-300 hover:underline" onClick={() => onSelect(c)}>Open case <ExternalLink size={11} /></button></div></Popup></CircleMarker>; })}
    </MapContainer><div className="pointer-events-none absolute left-3 top-3 z-[1000] rounded-lg border px-3 py-2 backdrop-blur" style={{ borderColor: "rgba(0,123,185,.35)", background: "rgba(6,15,26,.86)" }}><div className="label-mono text-cyan-300">GLOBAL SPILL SURVEILLANCE</div><div className="mt-1 text-[11px] text-slate-400">Click a marker for an evidence summary</div></div><div className="pointer-events-none absolute bottom-3 left-3 z-[1000] flex flex-wrap gap-2 rounded-lg border px-3 py-2 text-[10px] uppercase tracking-wider backdrop-blur" style={{ borderColor: "var(--border-default)", background: "rgba(6,15,26,.86)" }}>{Object.entries(COLORS).slice(0, 4).map(([k, color]) => <span key={k} className="flex items-center gap-1.5 text-slate-300"><i className="h-2 w-2 rounded-full" style={{ background: color }} />{k.replaceAll("_", " ")}</span>)}</div>
  </div>;
}

export default function Dashboard() {
  const { user } = useAuth(); const [params, setParams] = useSearchParams(); const nav = useNavigate();
  const view = ["pending", "probable"].includes(params.get("view")) ? params.get("view") : "all"; const origin = ["real", "imported", "demo", "all"].includes(params.get("origin")) ? params.get("origin") : "real";
  const [cases, setCases] = useState(null); const [alerts, setAlerts] = useState([]); const [stats, setStats] = useState(null); const [statsErr, setStatsErr] = useState(false); const [filter, setFilter] = useState("all"); const [query, setQuery] = useState(""); const [selected, setSelected] = useState(null); const [target, setTarget] = useState(null);
  const load = useCallback(async () => { const [c, a] = await Promise.all([api.get(`/cases?origin=${origin}&limit=1000`), api.get("/alerts")]); setCases(c.data); setAlerts(a.data); try { const s = await api.get("/dashboard/summary"); setStats(s.data); setStatsErr(false); } catch { setStatsErr(true); } }, [origin]);
  useEffect(() => { load().catch((e) => toast.error(apiError(e))); }, [load]); const live = useLive(); useEffect(() => { const a = live?.alerts?.[0]; if (a) setAlerts((p) => p.some((x) => x.id === a.id) ? p : [a, ...p]); }, [live?.alerts]); useEffect(() => { if (live?.lastJob?.status === "succeeded") load().catch(() => {}); }, [live?.lastJob, load]);
  const ack = async (id) => { try { await api.post(`/alerts/${id}/ack`); toast.success("Alert acknowledged"); load(); } catch (e) { toast.error(apiError(e)); } };
  const all = cases || []; const base = view === "pending" ? all.filter((c) => c.status === "open" && c.review_state === "pending") : view === "probable" ? all.filter((c) => ["probable", "analyst_confirmed"].includes(c.attribution_status)) : all; const shown = filter === "all" ? base : base.filter((c) => c.attribution_status === filter);
  const searchResults = useMemo(() => { const q = query.trim().toLowerCase(); if (!q) return []; const coord = parseCoord(query); return shown.filter((c) => `${c.case_number} ${c.id} ${c.confirmed_vessel_mmsi || ""} ${c.vessel_mmsi || ""} ${c.vessel_name || ""} ${c.source || ""}`.toLowerCase().includes(q) || (coord && coordsOf(c) && Math.abs(coordsOf(c)[0] - coord[0]) < 0.02 && Math.abs(coordsOf(c)[1] - coord[1]) < 0.02)).slice(0, 8); }, [query, shown]);
  const selectCase = (c) => { setSelected(c); const pos = coordsOf(c); if (pos) setTarget(pos); }; const executeSearch = () => { const coord = parseCoord(query); if (coord) { setTarget(coord); setSelected(null); toast.success(`Map centered on ${coord[0].toFixed(4)}, ${coord[1].toFixed(4)}`); return; } const hit = searchResults[0]; if (hit) selectCase(hit); else if (query.trim()) toast.error("No case, vessel, MMSI, or coordinate match"); }; const locateSpill = () => { const first = shown.find((c) => coordsOf(c)); if (!first) return toast.error("No mapped spill observations in this view"); selectCase(first); };
  const kv = (v) => (statsErr ? "UNAVAILABLE" : stats ? v : "—"); const kpis = [{ label: "Active cases", value: kv(stats?.active_cases), icon: Waves, color: "#ba1a1a", to: "/?origin=real" }, { label: "Probable / confirmed", value: kv(stats?.probable_confirmed), icon: Ship, color: "#c2410c", to: "/?origin=real&view=probable" }, { label: "Pending review", value: kv(stats?.pending_review), icon: Clock, color: "#b26a00", to: "/?origin=real&view=pending" }, { label: "AIS fixes indexed", value: kv(stats?.ais_fixes_indexed), icon: FileCheck, color: "#006194", to: "/ingest" }, { label: "Imported historical", value: kv(stats?.demo?.imported), icon: BookOpen, color: "#707881", to: "/?origin=imported" }];
  const analyzeEligible = async () => { try { const { data } = await api.post("/cases/analyze-eligible"); toast.success(`Queued ${data.queued.length} correlation run(s)`); setTimeout(() => load().catch(() => {}), 1500); } catch (e) { toast.error(apiError(e)); } };
  return <div className="flex h-full overflow-hidden"><main className="min-w-0 flex-1 overflow-y-auto p-4 sm:p-6"><div className="mb-4 flex flex-wrap items-end gap-3"><div className="mr-auto"><h1 className="font-display text-3xl font-extrabold tracking-tight sm:text-4xl">Spill Surveillance</h1><p className="label-mono mt-1">Map-first maritime oil-spill intelligence · Decision support — not a legal determination</p></div><button onClick={locateSpill} className="inline-flex items-center gap-2 rounded border px-3 py-2 font-mono text-[11px] uppercase tracking-wider text-cyan-300 hover:bg-cyan-400/10" style={{ borderColor: "rgba(0,97,148,.4)" }} data-testid="locate-spill"><Crosshair size={14} /> Locate spill</button></div>
    <div className="mb-4 grid grid-cols-2 gap-3 lg:grid-cols-3 xl:grid-cols-5">{kpis.map((k) => <button type="button" key={k.label} onClick={() => nav(k.to)} className="panel p-3 text-left transition-colors hover:border-cyan-400/40"><div className="flex items-center justify-between"><span className="label-mono">{k.label}</span><k.icon size={14} color={k.color} /></div><div className="mt-2 font-mono text-2xl font-semibold" style={{ color: k.color }}>{k.value}</div></button>)}</div>
    <div className="relative mb-4"><Search size={16} className="absolute left-3 top-3 text-slate-500" /><input value={query} onChange={(e) => setQuery(e.target.value)} onKeyDown={(e) => e.key === "Enter" && executeSearch()} placeholder="Search case, coordinates, MMSI, or vessel name…" className="w-full rounded-lg border bg-slate-950/60 py-2.5 pl-10 pr-24 text-sm text-slate-100 outline-none focus:border-cyan-400" style={{ borderColor: "var(--border-highlight)" }} data-testid="unified-case-search" /><button onClick={executeSearch} className="absolute right-2 top-1.5 rounded px-3 py-1.5 font-mono text-[10px] uppercase tracking-wider text-cyan-300">Search</button>{searchResults.length > 0 && <div className="absolute left-0 right-0 top-11 z-[1100] rounded-lg border p-1 shadow-2xl" style={{ background: "#f2f4f6", borderColor: "var(--border-highlight)" }}>{searchResults.map((c) => <button key={c.id} onClick={() => { selectCase(c); setQuery(""); }} className="flex w-full items-center justify-between rounded px-3 py-2 text-left text-xs hover:bg-slate-800"><span><b className="font-mono text-cyan-300">{c.case_number}</b><span className="ml-2 text-slate-300">{c.vessel_name || c.vessel_mmsi || c.source || "spill observation"}</span></span><span className="font-mono text-[10px] text-slate-500">{coordsOf(c)?.map((x) => x.toFixed(2)).join(", ") || "no coords"}</span></button>)}</div>}</div>
    <div className="grid gap-4 xl:grid-cols-[minmax(0,7fr)_minmax(280px,3fr)]"><CaseMap cases={shown} selected={selected} onSelect={selectCase} target={target} /><section className="panel min-h-[540px] overflow-hidden" data-testid="click-summary">{selected ? <div className="flex h-full flex-col"><div className="border-b p-4" style={{ borderColor: "var(--border-default)" }}><div className="label-mono text-cyan-300">CLICK-TO-SUMMARY</div><div className="mt-1 flex items-start justify-between gap-2"><h2 className="font-display text-xl font-semibold">{selected.case_number}</h2><StatusBadge status={selected.attribution_status} /></div><p className="mt-2 text-xs text-slate-400">{selected.source || "Satellite observation"} · acquired {fmtTime(selected.acquisition_time)}</p></div><div className="space-y-3 overflow-y-auto p-4 text-xs"><div className="grid grid-cols-2 gap-2"><div className="rounded border p-2" style={{ borderColor: "var(--border-default)" }}><span className="label-mono">Detection</span><b className="mt-1 block text-lg text-amber-300">{selected.detection_confidence_source === "detector" ? pct(selected.detection_confidence) : "N/A"}</b></div><div className="rounded border p-2" style={{ borderColor: "var(--border-default)" }}><span className="label-mono">Candidates</span><b className="mt-1 block text-lg text-cyan-300">{selected.candidate_count ?? "—"}</b></div></div><div className="font-mono text-slate-400">Coordinates: {coordsOf(selected)?.map((x) => x.toFixed(5)).join(", ") || "not available"}</div><div className="font-mono text-slate-400">Jurisdiction: {selected.primary_jurisdiction?.code || "unassigned"}</div><p className="leading-relaxed text-slate-300">{selected.review_state === "pending" ? "Awaiting analyst review. Open the case to inspect evidence, AIS correlation, and provenance." : "Stored evidence is available for investigation and verification."}</p><button onClick={() => nav(`/cases/${selected.id}`)} className="inline-flex items-center justify-center gap-2 rounded bg-cyan-400/15 px-3 py-2 font-mono text-[11px] uppercase tracking-wider text-cyan-300">Open full case <ExternalLink size={13} /></button></div></div> : <div className="grid h-full place-items-center p-8 text-center"><div><Crosshair className="mx-auto mb-3 text-slate-600" size={30} /><h2 className="font-display text-lg text-slate-300">Select a spill marker</h2><p className="mt-1 text-xs text-slate-500">Click the map or search for a case, coordinate, MMSI, or vessel.</p></div></div>}</section></div>
    <div className="mt-4 panel overflow-hidden"><div className="flex flex-wrap items-center gap-2 border-b px-4 py-3" style={{ borderColor: "var(--border-default)" }}><h2 className="mr-auto font-display text-lg font-semibold">Investigation cases · {shown.length}</h2>{["real", "imported", "demo", "all"].map((o) => <button key={o} onClick={() => setParams({ origin: o, ...(view !== "all" ? { view } : {}) })} className={`rounded-full border px-2.5 py-1 font-mono text-[10px] uppercase tracking-wider ${origin === o ? "border-emerald-400/40 bg-emerald-400/15 text-emerald-300" : "border-slate-700 text-slate-400"}`}>{o}</button>)}{hasRole(user, "supervisor") && origin === "real" && <button onClick={analyzeEligible} className="rounded-full border border-cyan-400/40 px-3 py-1 font-mono text-[10px] uppercase tracking-wider text-cyan-300">Analyze eligible cases</button>}{["all", "probable", "possible", "indeterminate", "insufficient_evidence", "analyst_confirmed"].map((f) => <button key={f} onClick={() => setFilter(f)} className={`rounded-full border px-2.5 py-1 font-mono text-[10px] uppercase tracking-wider ${filter === f ? "border-cyan-400/40 bg-cyan-400/15 text-cyan-300" : "border-slate-700 text-slate-400"}`}>{f.replaceAll("_", " ")}</button>)}</div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="label-mono text-left">{["Case", "Acquired (UTC)", "Source", "Det. conf", "Attribution", "Review"].map((h) => <th key={h} className="px-4 py-2 font-normal">{h}</th>)}</tr></thead><tbody>{shown.map((c) => <tr key={c.id} onClick={() => selectCase(c)} className="cursor-pointer border-t transition-colors hover:bg-slate-800/50" style={{ borderColor: "var(--border-default)" }}><td className="px-4 py-3 font-mono text-cyan-300">{c.case_number}</td><td className="px-4 py-3 font-mono text-xs text-slate-300">{fmtTime(c.acquisition_time)}</td><td className="px-4 py-3 text-xs text-slate-400">{c.source}</td><td className="px-4 py-3 font-mono text-xs">{c.detection_confidence_source === "detector" ? pct(c.detection_confidence) : "N/A"}</td><td className="px-4 py-3"><StatusBadge status={c.attribution_status} /></td><td className="px-4 py-3 font-mono text-[10px] uppercase text-slate-400">{c.review_state}</td></tr>)}{cases === null && <tr><td colSpan={6} className="px-4 py-8 text-center text-slate-500">Loading case layer…</td></tr>}{cases !== null && shown.length === 0 && <tr><td colSpan={6} className="px-4 py-8 text-center text-slate-500">No cases match this view.</td></tr>}</tbody></table></div></div>
  </main><aside className="hidden w-80 shrink-0 flex-col border-l xl:flex" style={{ borderColor: "var(--border-default)", background: "var(--bg-secondary)" }}><div className="flex items-center gap-2 border-b px-4 py-3" style={{ borderColor: "var(--border-default)" }}><ShieldAlert size={14} color="#ba1a1a" /><h2 className="font-display font-semibold">Alerts</h2><span className="ml-auto font-mono text-xs text-slate-400">{alerts.filter((a) => !a.acknowledged).length} open</span></div><div className="border-b p-3" style={{ borderColor: "var(--border-default)" }}><DetectorPrecision /></div><div className="flex-1 space-y-2 overflow-y-auto p-3">{alerts.length === 0 && <p className="p-3 text-xs text-slate-500">No alerts raised.</p>}{alerts.map((a) => <div key={a.id} className="rounded-md border p-3 text-xs" style={{ borderColor: a.acknowledged ? "var(--border-default)" : "rgba(186,26,26,0.5)" }}><div className="flex items-center justify-between"><button className="font-mono text-cyan-300 hover:underline" onClick={() => nav(`/cases/${a.case_id}`)}>{a.case_number}</button><span className="font-mono text-[10px] text-slate-500">{fmtTime(a.created_at)}</span></div><p className="mt-1.5 text-slate-300">{a.message}</p>{!a.acknowledged && hasRole(user, "supervisor") && <button onClick={() => ack(a.id)} className="mt-2 inline-flex items-center gap-1 font-mono text-[10px] uppercase text-emerald-300"><Check size={12} /> Acknowledge</button>}</div>)}</div></aside></div>;
}
